mode: auto

head:
  js:
    async:
      # è¿™é‡Œæ˜¯ä½ ä» iconfont å¤„è·å¾—çš„å›¾æ ‡é“¾æ¥ã€‚
      iconfont: //at.alicdn.com/t/font_2833682_qn2a2qwzhnp.js
      

# é¦–é¡µæ ‡è¯­åŠ¨ç”»
banner:
  title: 
    - Yuumi
    - çš„
    - çƒŸ
    - æ³¢
    - ä¹‹
    - è·¯
  cloud:
    color: "#fcf696"

# ç½‘ç«™å›¾æ ‡
favicon: /yuumi.png

# è¾¹æ 
sidebar:
  bg_image: /images/settings/Yuumi_Icon.png
  dark_bg_image: /images/settings/Yuumi_Icon.png
  bg_position: bottom 1rem center

# é»˜å“€æ—¥
mourn:
  enable: true
  days:
    - "4-4"
    - "12-1"

# ä¸»é¢˜è‰²
colors:
  primary: "#D69B54"
  # bg: "#F5F5F5"
  selection_bg: '#a25430' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  tag_start_color: '#a25430'
  tag_end_color: '#d3862e'
  dark:
    block: '#1e2d31'
  inverse: '#8e71c1'
  success: '#a2bd2c'
  warning: '#f2711c'
  danger: '#dc706d'
  info: '#7ec6e3'
  link: '#7f91c8'

# èƒŒæ™¯å›¾ç‰‡
bg_image:
  url: /images/settings/background.png
  dark: /images/settings/bgdark.jpg
  opacity: 1

# çƒŸèŠ±
fireworks:
  colors:
    - "255, 229, 125"   # é»„è‰²
    - "255, 205, 136"   # æ©™è‰²
    - "230, 244, 173"   # ç»¿è‰²

# å¤´åƒ
avatar:
  url: /images/settings/favicon.ico
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ’›
    message: Looking for dawn.


# ç¤¾äº¤
social:
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: http://music.163.com/artist?id=30377410&userid=436730182
    icon: ri:netease-cloud-music-line
    color: "#C10D0C"
  - name: å¾®åš
    link: https://weibo.com/u/3075122387
    icon: ri:weibo-line
    color: "#E6162D"
  - name: bilibili
    link: https://space.bilibili.com/7498906
    icon: ri:bilibili-line
    color: "#FF8EB3"
  - name: Notion
    link: https://yuumis.notion.site
    icon: icon-notion
    color: "#717171"
  - name: GitHub
    link: https://github.com/Yuumi0221
    icon: ri:github-line
    color: "#9b9b9b"
  - name: E-Mail
    link: mailto:yuumi0221@outlook.com
    icon: ri:mail-line
    color: "#8E71C1"
  - name: Pixiv
    link: https://www.pixiv.net/users/10168567
    icon: icon-pixiv-copy
    # color: "#0096FA"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/yuumi-81
    icon: ri:zhihu-line
    color: "#0084FF"
  - name: Twitter
    link: https://twitter.com/Yuumi12118924
    icon: ri:twitter-line
    color: "#1da1f2"

# å¯¼èˆª


# æ–‡ç« 
   # å†…å®¹å¡ç‰‡ 
post_card:
  opacity: 0.8
  
   # å†…å®¹ä¿¡æ¯
post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

# ä»£ç é«˜äº®
codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

# ç‰ˆæƒ
creative_commons:
  clipboard: false

# é¡µè„š
footer:
  since: 2021
  icon:
    color: "#d69b54"

katex:
  copy_tex: true

# ç¼–è¾‘
post_edit:
  enable: false

  # æ‰“é’±
reward:
  enable: true
  comment: å†…ä¸ªâ€¦â€¦å¦‚æœå¯ä»¥çš„è¯â€¦â€¦
  methods:
    - name: æ”¯ä»˜å®
      path: /images/settings/zfb.jpg
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: /images/settings/wx.png
      color: "#2DC100"
      icon: ri:wechat-pay-line
    - name: QQ æ”¯ä»˜
      path: /images/settings/qq.png
      color: "#12B7F5"
      icon: ri:qq-line

# æ ‡ç­¾
wordcloud:
  enable: false
  height: 450

# è¯„è®º
comment:
  candidates:
    - waline
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/Yuumi0221/Yuumi0221.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµ

waline:
  enable: true
  serverURL: https://comment.yuumi.link
  visitor: true
  comment: true
  locale:
    placeholder: å¡«å†™qqé‚®ç®±æˆ–ç‚¹å‡»ç™»å½•ï¼Œå¯ä»¥å±•ç¤ºä¸ªäººå¤´åƒ~è¯¦æƒ…è¯·è§ã€ç•™è¨€æ¿ã€‘æ¿å—
  requiredMeta: [nick]
  emoji: 
    - https://unpkg.com/@waline/emojis@1.1.0/bmoji
    - https://unpkg.com/@waline/emojis@1.1.0/weibo
    - https://unpkg.com/@waline/emojis@1.1.0/qq
    - https://unpkg.com/@waline/emojis@1.1.0/tieba
  reaction: 
    - https://unpkg.com/@waline/emojis@1.1.0/bmoji/bmoji_thumb_up.png
    - https://unpkg.com/@waline/emojis@1.1.0/bmoji/bmoji_call.png
    - https://unpkg.com/@waline/emojis@1.1.0/bmoji/bmoji_not_open.png
    - https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_satisfied.png
    - https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_cry.png
    - https://unpkg.com/@waline/emojis@1.1.0/tw/1f605.png


# CDN
vendors:
  host: 'https://fastly.jsdelivr.net/npm/'

# pjax
pjax:
  enable: true


github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: Yuumi
  apikey: # ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: Yuumi0221/Yuumi0221.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: auto

# å¼•æ“æœç´¢
engine_search:
  enable: false

# æœ¬åœ°æœç´¢
local_search:
  enable: true
# è°·æ­Œåˆ†æ
google_analytics:
  enable: false
  id: G-SZSXG7VRWS

# ä¸è’œå­ç»Ÿè®¡
busuanzi:
  enable: false
  site_uv: true
  site_uv_icon: ri:user-line
  site_pv: true
  site_pv_icon: ri:eye-line
  page_pv: true
  page_pv_icon: ri:eye-line

leancloud_visitors:
  enable: true
  app_id: s3GDW9HqA7RyI3bPpqhxcdcS-MdYXbMMI
  app_key: KBqwPHjmw23zVj5dzbd3sFaM


albums:
  enable: true

girls:
  enable: false

# tagsé¢œè‰²
tags:
  åŠ¨ç”»: orange
  éŸ³ä¹: crimson
  æ•™ç¨‹: royalblue
  ç¬”è®°: dimgray
  åˆ†äº«: "#bc4d48"
  éšç¬”: mediumpurple
  æ¸¸æˆ: "#d04d2d"
  èµ„æº: "#2577b1"
  æ—¥è®°: "#ccb44b"
  #äº‘æ¸¸å›é…ç½®
  Parcel: "#21374b"
  å­¦ä¹ : saddlebrown
  éƒ¨è½: "#DD306A"
  ç§‘å¹»: midnightblue

  # yunä¸»é¢˜é…ç½®
  Vue: "#4fc08d"
  Hexo: "#0E83CD"
  CSS: "#5298d1"
  Node.js: "#026E00"
  Git: "#F14E32"
  React: "#61dafb"
  Python: "#3776ab"
  PHP: "#8892BF"
  VS Code: "#0066B8"
  JavaScript: "#F4DF4F"
  TypeScript: "#317AC6"
  Laravel: "#F4645F"

# åˆ†ç±»é¢œè‰²
# categories:
  # å°åˆ†äº«: "#bc4d48"

# Extra links
pages:
  - name: ç•™è¨€æ¿
    url: /comment/
    icon: ri:clipboard-line
    color: "#737de5"
  - name: ç›¸å†Œ
    url: /albums/
    icon: ri:gallery-line
    color: "#43abee"
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:open-arm-line
    color: "#4bbea4"

menu:
  custom:
    title: å¹»ç¯ç‰‡
    path: /slides/
    icon: ri:keynote-line

cursor:
  enable: true

baidu_push: true

# å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  count: true
  time: true

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn/?c=k&c=d&c=i

custom:
  style: source/_data/style/*